### PR TITLE
Update to stateless function

### PR DESCRIPTION
**Pull request by otakustay**
- There is no need for `shouldComponentUpdate`
- Test enabled via jest

Since this update requires `react>=0.14` so it introduces breaking change

### CODE REVIEW

**Comment by otakustay** [comment]
I'd recommend it to be a major version since react version is changed

**Comment by misund** [comment]
I think maybe this is a slight overkill for a noop component. The function itself is fine, but we don't really need babel, jest testing and so on. Or react-dom, for that matter. This component should be really simple.

**Comment by otakustay** [comment]
OK, I'll remove these

**Comment by otakustay** [comment]
@misund Would you mind take a look at this PR?

**Review by misund — APPROVED** [review]

**Pull request merged**
